FROM maven:3.8-openjdk-11 AS build
RUN apt-get update 


# Add nodejs 
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash \
  && export NVM_DIR="$HOME/.nvm" \
  && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
  && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" \
  && nvm install v16.17.1 \
  && node -v \
  && npm -v


RUN mkdir /Codedefenders/
WORKDIR /Codedefenders/
COPY ./local-repo ./local-repo/
COPY pom.xml .
# Download dependencies before copying the source code as the dependencies don't change that often
#RUN mvn dependency:go-offline

#RUN mvn test
COPY ./src ./src/
COPY ./.git ./.git/
COPY package.json .
COPY rollup.config.js .
COPY checkstyle-codedefenders.xml .
#RUN mvn test